name: supplier
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Enhance UI :
  cupertino_icons: ^1.0.5
  pinput: ^2.2.31
  dropdown_button2: ^1.9.4
  image_picker: ^1.0.1
  intl_phone_field: ^3.2.0

  # Local Database :
  shared_preferences: ^2.0.15

  # Animation :
  lottie: ^2.4.0

  # Fetch server data & State management :
  get: ^4.6.5
  http: ^0.13.6
  internet_connection_checker: ^1.0.0+1
  loading_animation_widget: ^1.2.0+4
  shimmer: ^3.0.0
  rxdart: ^0.27.7

  # Payment :
  razorpay_flutter: ^1.3.5

  # Image View :
  flutter_svg: ^2.0.7
  cached_network_image: ^3.2.3

  # Utills :
  share_plus: ^7.0.2

  # Web module :
  url_launcher: ^6.1.7
  webview_flutter: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    -
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-BoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins/Poppins-LightItalic.ttf
          weight: 300
          style: italic
